import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Shell from "../components/shell";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className="flex min-h-screen bg-slate-50">
      <Head>
        <title>Aros</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/aroslogo.png" />
      </Head>
      <main className="bg-slate-50 w-full h-screen">
        <Shell />
      </main>
    </div>
  )
}
